/**
 * States/Provinces data mapped to countries
 * Static data to replace external API dependency
 * 
 * TODO: Replace with proper API integration
 * This static data should eventually be fetched from a reliable geographical API service
 * The current implementation only includes major countries and may need expansion
 * Consider dynamic loading based on country selection to reduce bundle size
 */

export interface State {
  name: string;
  code?: string; // State code (if applicable)
}

export interface SelectOption {
  value: string;
  label: string;
}

/**
 * Mapping of country names to their states/provinces
 */
export const COUNTRY_STATES: Record<string, State[]> = {
  "United States": [
    { name: "Alabama", code: "AL" },
    { name: "Alaska", code: "AK" },
    { name: "Arizona", code: "AZ" },
    { name: "Arkansas", code: "AR" },
    { name: "California", code: "CA" },
    { name: "Colorado", code: "CO" },
    { name: "Connecticut", code: "CT" },
    { name: "Delaware", code: "DE" },
    { name: "Florida", code: "FL" },
    { name: "Georgia", code: "GA" },
    { name: "Hawaii", code: "HI" },
    { name: "Idaho", code: "ID" },
    { name: "Illinois", code: "IL" },
    { name: "Indiana", code: "IN" },
    { name: "Iowa", code: "IA" },
    { name: "Kansas", code: "KS" },
    { name: "Kentucky", code: "KY" },
    { name: "Louisiana", code: "LA" },
    { name: "Maine", code: "ME" },
    { name: "Maryland", code: "MD" },
    { name: "Massachusetts", code: "MA" },
    { name: "Michigan", code: "MI" },
    { name: "Minnesota", code: "MN" },
    { name: "Mississippi", code: "MS" },
    { name: "Missouri", code: "MO" },
    { name: "Montana", code: "MT" },
    { name: "Nebraska", code: "NE" },
    { name: "Nevada", code: "NV" },
    { name: "New Hampshire", code: "NH" },
    { name: "New Jersey", code: "NJ" },
    { name: "New Mexico", code: "NM" },
    { name: "New York", code: "NY" },
    { name: "North Carolina", code: "NC" },
    { name: "North Dakota", code: "ND" },
    { name: "Ohio", code: "OH" },
    { name: "Oklahoma", code: "OK" },
    { name: "Oregon", code: "OR" },
    { name: "Pennsylvania", code: "PA" },
    { name: "Rhode Island", code: "RI" },
    { name: "South Carolina", code: "SC" },
    { name: "South Dakota", code: "SD" },
    { name: "Tennessee", code: "TN" },
    { name: "Texas", code: "TX" },
    { name: "Utah", code: "UT" },
    { name: "Vermont", code: "VT" },
    { name: "Virginia", code: "VA" },
    { name: "Washington", code: "WA" },
    { name: "West Virginia", code: "WV" },
    { name: "Wisconsin", code: "WI" },
    { name: "Wyoming", code: "WY" },
  ],
  Canada: [
    { name: "Alberta", code: "AB" },
    { name: "British Columbia", code: "BC" },
    { name: "Manitoba", code: "MB" },
    { name: "New Brunswick", code: "NB" },
    { name: "Newfoundland and Labrador", code: "NL" },
    { name: "Northwest Territories", code: "NT" },
    { name: "Nova Scotia", code: "NS" },
    { name: "Nunavut", code: "NU" },
    { name: "Ontario", code: "ON" },
    { name: "Prince Edward Island", code: "PE" },
    { name: "Quebec", code: "QC" },
    { name: "Saskatchewan", code: "SK" },
    { name: "Yukon", code: "YT" },
  ],
  Australia: [
    { name: "Australian Capital Territory", code: "ACT" },
    { name: "New South Wales", code: "NSW" },
    { name: "Northern Territory", code: "NT" },
    { name: "Queensland", code: "QLD" },
    { name: "South Australia", code: "SA" },
    { name: "Tasmania", code: "TAS" },
    { name: "Victoria", code: "VIC" },
    { name: "Western Australia", code: "WA" },
  ],
  "United Kingdom": [
    { name: "England" },
    { name: "Scotland" },
    { name: "Wales" },
    { name: "Northern Ireland" },
  ],
  Germany: [
    { name: "Baden-Württemberg" },
    { name: "Bavaria" },
    { name: "Berlin" },
    { name: "Brandenburg" },
    { name: "Bremen" },
    { name: "Hamburg" },
    { name: "Hesse" },
    { name: "Lower Saxony" },
    { name: "Mecklenburg-Vorpommern" },
    { name: "North Rhine-Westphalia" },
    { name: "Rhineland-Palatinate" },
    { name: "Saarland" },
    { name: "Saxony" },
    { name: "Saxony-Anhalt" },
    { name: "Schleswig-Holstein" },
    { name: "Thuringia" },
  ],
  France: [
    { name: "Auvergne-Rhône-Alpes" },
    { name: "Bourgogne-Franche-Comté" },
    { name: "Brittany" },
    { name: "Centre-Val de Loire" },
    { name: "Corsica" },
    { name: "Grand Est" },
    { name: "Hauts-de-France" },
    { name: "Île-de-France" },
    { name: "Normandy" },
    { name: "Nouvelle-Aquitaine" },
    { name: "Occitanie" },
    { name: "Pays de la Loire" },
    { name: "Provence-Alpes-Côte d'Azur" },
  ],
  Italy: [
    { name: "Abruzzo" },
    { name: "Aosta Valley" },
    { name: "Apulia" },
    { name: "Basilicata" },
    { name: "Calabria" },
    { name: "Campania" },
    { name: "Emilia-Romagna" },
    { name: "Friuli-Venezia Giulia" },
    { name: "Lazio" },
    { name: "Liguria" },
    { name: "Lombardy" },
    { name: "Marche" },
    { name: "Molise" },
    { name: "Piedmont" },
    { name: "Sardinia" },
    { name: "Sicily" },
    { name: "Trentino-South Tyrol" },
    { name: "Tuscany" },
    { name: "Umbria" },
    { name: "Veneto" },
  ],
  Spain: [
    { name: "Andalusia" },
    { name: "Aragon" },
    { name: "Asturias" },
    { name: "Balearic Islands" },
    { name: "Basque Country" },
    { name: "Canary Islands" },
    { name: "Cantabria" },
    { name: "Castile and León" },
    { name: "Castile-La Mancha" },
    { name: "Catalonia" },
    { name: "Extremadura" },
    { name: "Galicia" },
    { name: "La Rioja" },
    { name: "Madrid" },
    { name: "Murcia" },
    { name: "Navarre" },
    { name: "Valencia" },
  ],
  Mexico: [
    { name: "Aguascalientes" },
    { name: "Baja California" },
    { name: "Baja California Sur" },
    { name: "Campeche" },
    { name: "Chiapas" },
    { name: "Chihuahua" },
    { name: "Coahuila" },
    { name: "Colima" },
    { name: "Durango" },
    { name: "Guanajuato" },
    { name: "Guerrero" },
    { name: "Hidalgo" },
    { name: "Jalisco" },
    { name: "Mexico City" },
    { name: "Mexico State" },
    { name: "Michoacán" },
    { name: "Morelos" },
    { name: "Nayarit" },
    { name: "Nuevo León" },
    { name: "Oaxaca" },
    { name: "Puebla" },
    { name: "Querétaro" },
    { name: "Quintana Roo" },
    { name: "San Luis Potosí" },
    { name: "Sinaloa" },
    { name: "Sonora" },
    { name: "Tabasco" },
    { name: "Tamaulipas" },
    { name: "Tlaxcala" },
    { name: "Veracruz" },
    { name: "Yucatán" },
    { name: "Zacatecas" },
  ],
  Brazil: [
    { name: "Acre", code: "AC" },
    { name: "Alagoas", code: "AL" },
    { name: "Amapá", code: "AP" },
    { name: "Amazonas", code: "AM" },
    { name: "Bahia", code: "BA" },
    { name: "Ceará", code: "CE" },
    { name: "Distrito Federal", code: "DF" },
    { name: "Espírito Santo", code: "ES" },
    { name: "Goiás", code: "GO" },
    { name: "Maranhão", code: "MA" },
    { name: "Mato Grosso", code: "MT" },
    { name: "Mato Grosso do Sul", code: "MS" },
    { name: "Minas Gerais", code: "MG" },
    { name: "Pará", code: "PA" },
    { name: "Paraíba", code: "PB" },
    { name: "Paraná", code: "PR" },
    { name: "Pernambuco", code: "PE" },
    { name: "Piauí", code: "PI" },
    { name: "Rio de Janeiro", code: "RJ" },
    { name: "Rio Grande do Norte", code: "RN" },
    { name: "Rio Grande do Sul", code: "RS" },
    { name: "Rondônia", code: "RO" },
    { name: "Roraima", code: "RR" },
    { name: "Santa Catarina", code: "SC" },
    { name: "São Paulo", code: "SP" },
    { name: "Sergipe", code: "SE" },
    { name: "Tocantins", code: "TO" },
  ],
  India: [
    { name: "Andhra Pradesh" },
    { name: "Arunachal Pradesh" },
    { name: "Assam" },
    { name: "Bihar" },
    { name: "Chhattisgarh" },
    { name: "Goa" },
    { name: "Gujarat" },
    { name: "Haryana" },
    { name: "Himachal Pradesh" },
    { name: "Jharkhand" },
    { name: "Karnataka" },
    { name: "Kerala" },
    { name: "Madhya Pradesh" },
    { name: "Maharashtra" },
    { name: "Manipur" },
    { name: "Meghalaya" },
    { name: "Mizoram" },
    { name: "Nagaland" },
    { name: "Odisha" },
    { name: "Punjab" },
    { name: "Rajasthan" },
    { name: "Sikkim" },
    { name: "Tamil Nadu" },
    { name: "Telangana" },
    { name: "Tripura" },
    { name: "Uttar Pradesh" },
    { name: "Uttarakhand" },
    { name: "West Bengal" },
  ],
  Japan: [
    { name: "Hokkaido" },
    { name: "Aomori" },
    { name: "Iwate" },
    { name: "Miyagi" },
    { name: "Akita" },
    { name: "Yamagata" },
    { name: "Fukushima" },
    { name: "Ibaraki" },
    { name: "Tochigi" },
    { name: "Gunma" },
    { name: "Saitama" },
    { name: "Chiba" },
    { name: "Tokyo" },
    { name: "Kanagawa" },
    { name: "Niigata" },
    { name: "Toyama" },
    { name: "Ishikawa" },
    { name: "Fukui" },
    { name: "Yamanashi" },
    { name: "Nagano" },
    { name: "Gifu" },
    { name: "Shizuoka" },
    { name: "Aichi" },
    { name: "Mie" },
    { name: "Shiga" },
    { name: "Kyoto" },
    { name: "Osaka" },
    { name: "Hyogo" },
    { name: "Nara" },
    { name: "Wakayama" },
    { name: "Tottori" },
    { name: "Shimane" },
    { name: "Okayama" },
    { name: "Hiroshima" },
    { name: "Yamaguchi" },
    { name: "Tokushima" },
    { name: "Kagawa" },
    { name: "Ehime" },
    { name: "Kochi" },
    { name: "Fukuoka" },
    { name: "Saga" },
    { name: "Nagasaki" },
    { name: "Kumamoto" },
    { name: "Oita" },
    { name: "Miyazaki" },
    { name: "Kagoshima" },
    { name: "Okinawa" },
  ],
  "United Arab Emirates": [
    { name: "Abu Dhabi" },
    { name: "Dubai" },
    { name: "Sharjah" },
    { name: "Ajman" },
    { name: "Umm Al-Quwain" },
    { name: "Fujairah" },
    { name: "Ras Al Khaimah" },
  ],
};

/**
 * Get states for a specific country
 */
export function getStatesForCountry(countryName: string): State[] {
  return COUNTRY_STATES[countryName] || [];
}

/**
 * Transform states to select options
 */
export function getStateSelectOptions(countryName: string): SelectOption[] {
  const states = getStatesForCountry(countryName);
  return states
    .map((state) => ({
      value: state.name,
      label: state.name,
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
}

/**
 * Check if a country has states/provinces
 */
export function countryHasStates(countryName: string): boolean {
  return (
    countryName in COUNTRY_STATES && COUNTRY_STATES[countryName].length > 0
  );
}
